version: '3'
services:
  neo4j:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'neo4j:latest'
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
volumes:
  neo4j_data:
    driver: local
